name: ✨ Feature request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Have an idea to make **Neoly** better?  
        We’d love to hear it.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the pain point or limitation.
      placeholder: I find it difficult to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like Neoly to work?
      placeholder: It would be great if Neoly could...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered (optional)
      description: Any other solutions you’ve thought about?

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Screenshots, examples, or references.
